services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-${ENVIRONMENT}
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "${MSSQL_PID}"
      SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "${MSSQL_PORT}:1433"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./mnt/mssql-data/${ENVIRONMENT}/data:/var/opt/mssql/data
      - ./mnt/mssql-data/${ENVIRONMENT}/logs:/var/opt/mssql/log
      - ./mnt/mssql-data/${ENVIRONMENT}/backups:/var/opt/mssql/backups
    deploy:
      resources:
        limits:
          memory: ${MSSQL_MEMORY}
          cpus: "${MSSQL_CPUS}"
